import type { Animal, BreedingEvent, HealthRecord, MatingGroup } from "@shared/schema";
import { calculateLambStage } from "@shared/lamb-stage";

export type ExportRow = Record<string, string | number | null>;
const d = (v?: string | Date | null) => (v ? new Date(v).toISOString().slice(0, 10) : "");
const age = (birth?: string | null, when?: string | null) => (birth && when ? Math.round((new Date(when).getTime() - new Date(birth).getTime()) / 86400000) : null);

export const isValid100DayRange = (a: number | null) => a !== null && a >= 90 && a <= 115;
export const isValid270DayRange = (a: number | null) => a !== null && a >= 260 && a <= 320;

export const LAMB_BIRTH_HEADERS = ["Lamb ID","Birth date","Sex","Sire/father ID","Dam/mother ID","Birth status","Birth type","Birth weight","Electronic ID","Tattoo ID","Tag/chip ID","Stud prefix","Breed","Season/lambing code","Management group","Environmental group","Weaning/speen status","Lamb stage","Notes"] as const;
export const LAMB_PERFORMANCE_HEADERS = ["Lamb ID","100-day weigh date","100-day weight","Age at 100-day weighing","100-day valid range indicator","270-day/post-wean weigh date","270-day/post-wean weight","Age at 270-day/post-wean weighing","270-day valid range indicator","Latest/current weight","Weight date","Management group","Environmental group","Notes"] as const;
export const MATING_DEK_HEADERS = ["Ram/sire ID","Ewe IDs","Mating group name/code","Date ram in","Date ram out","Season/lambing code","Management group","Environmental group","Notes"] as const;
export const EWE_EXPORT_HEADERS = ["Ewe ID","Electronic ID / tattoo / tag","Date of birth","Age","Breed","Status","Stud/commercial class","Sire ID","Dam ID","Mating group","Current sire/ram assigned","Lambing season code","Lambs born total","Lambs weaned total","Singles/twins/triplets","Abortions/stillborn/dead-at-birth","Last lambing date","Last lamb IDs","Latest weight","Health summary","Cull/sale/death reason","Notes"] as const;
export const RAM_EXPORT_HEADERS = ["Ram ID","Electronic ID / tattoo / tag","Date of birth","Age","Breed","Status","Stud/commercial class","Sire ID","Dam ID","Assigned ewe group","Mating date in","Mating date out","Number of ewes joined","Number of lambs born from this sire","Number of lambs weaned from this sire","Average 100-day progeny weight","Average 270-day progeny weight","Latest weight","Health summary","Cull/sale/death reason","Notes"] as const;
export const CULL_SOLD_HEADERS = ["Animal ID","Sex","Breed","Date of birth","Status","Status date","Reason","Sire","Dam","Latest weight","Last known group","Buyer/recipient","Price","Notes"] as const;

export const buildLambBirthRows = (l: Animal[]): ExportRow[] => l.map(a => ({"Lamb ID":a.tagId||"","Birth date":d(a.birthDate),"Sex":a.sex||"","Sire/father ID":a.externalSireInfo||"","Dam/mother ID":a.externalDamInfo||"","Birth status":a.birthStatus||"","Birth type":a.birthStatus||"","Birth weight":a.birthWeight??"","Electronic ID":a.electronicId||"","Tattoo ID":a.tattooId||"","Tag/chip ID":a.tagId||"","Stud prefix":a.studPrefix||"","Breed":a.breed||"","Season/lambing code":a.lambingSeason||"","Management group":a.managementGroup||"","Environmental group":a.environmentGroup||"","Weaning/speen status":a.weaningStatus||"","Lamb stage":calculateLambStage(a).label,"Notes":a.notes||""}));

export const buildLambPerformanceRows = (l: Animal[]): ExportRow[] => l.map(a => { const a100=age(a.birthDate,a.weight100DayDate); const a270=age(a.birthDate,a.weight270DayDate); return {"Lamb ID":a.tagId||"","100-day weigh date":d(a.weight100DayDate),"100-day weight":a.weight100Day??"","Age at 100-day weighing":a100??"","100-day valid range indicator":isValid100DayRange(a100)?"valid":"invalid","270-day/post-wean weigh date":d(a.weight270DayDate),"270-day/post-wean weight":a.weight270Day??"","Age at 270-day/post-wean weighing":a270??"","270-day valid range indicator":isValid270DayRange(a270)?"valid":"invalid","Latest/current weight":a.currentWeight??"","Weight date":d(a.weight270DayDate),"Management group":a.managementGroup||"","Environmental group":a.environmentGroup||"","Notes":a.notes||""}; });

export const buildMatingDekRows = (g: MatingGroup[]): ExportRow[] => g.map(m=>({"Ram/sire ID":String(m.ramId||""),"Ewe IDs":(m.eweIds||[]).join(","),"Mating group name/code":m.name||"","Date ram in":d(m.dateIn),"Date ram out":d(m.dateOut),"Season/lambing code":m.lambingSeason||"","Management group":m.managementGroup||"","Environmental group":m.environmentGroup||"","Notes":m.notes||""}));

export const buildEweExportRows = (e: Animal[], b: BreedingEvent[] = [], h: HealthRecord[] = []): ExportRow[] => e.map(a=>({"Ewe ID":a.tagId||"","Electronic ID / tattoo / tag":[a.electronicId,a.tattooId,a.tagId].filter(Boolean).join(" / "),"Date of birth":d(a.birthDate),"Age":a.birthDate?Math.floor((Date.now()-new Date(a.birthDate).getTime())/86400000):"","Breed":a.breed||"","Status":a.status||"","Stud/commercial class":a.classification||"","Sire ID":a.externalSireInfo||"","Dam ID":a.externalDamInfo||"","Mating group":"","Current sire/ram assigned":"","Lambing season code":a.lambingSeason||"","Lambs born total":b.filter(x=>x.eweId===a.id).reduce((s,x)=>s+(x.lambCount||0),0),"Lambs weaned total":"","Singles/twins/triplets":"","Abortions/stillborn/dead-at-birth":"","Last lambing date":d(b.filter(x=>x.eweId===a.id).sort((x,y)=>String(y.matingDate).localeCompare(String(x.matingDate)))[0]?.matingDate as any),"Last lamb IDs":"","Latest weight":a.currentWeight??"","Health summary":`${h.filter(x=>x.animalId===a.id).length} records`,"Cull/sale/death reason":a.removalReason||a.cullReason||"","Notes":a.notes||""}));

export const buildRamExportRows = (r: Animal[], b: BreedingEvent[] = [], lambs: Animal[] = [], h: HealthRecord[] = []): ExportRow[] => r.map(a=>({"Ram ID":a.tagId||"","Electronic ID / tattoo / tag":[a.electronicId,a.tattooId,a.tagId].filter(Boolean).join(" / "),"Date of birth":d(a.birthDate),"Age":a.birthDate?Math.floor((Date.now()-new Date(a.birthDate).getTime())/86400000):"","Breed":a.breed||"","Status":a.status||"","Stud/commercial class":a.classification||"","Sire ID":a.externalSireInfo||"","Dam ID":a.externalDamInfo||"","Assigned ewe group":"","Mating date in":"","Mating date out":"","Number of ewes joined":b.filter(x=>x.ramId===a.id).length,"Number of lambs born from this sire":lambs.filter(x=>x.externalSireInfo===a.tagId).length,"Number of lambs weaned from this sire":"","Average 100-day progeny weight":"","Average 270-day progeny weight":"","Latest weight":a.currentWeight??"","Health summary":`${h.filter(x=>x.animalId===a.id).length} records`,"Cull/sale/death reason":a.removalReason||a.cullReason||"","Notes":a.notes||""}));

export const buildCullSoldRows = (a: Animal[]): ExportRow[] => a.map(x=>({"Animal ID":x.tagId||"","Sex":x.sex||"","Breed":x.breed||"","Date of birth":d(x.birthDate),"Status":x.status||"","Status date":d(x.cullDate),"Reason":x.removalReason||x.cullReason||"","Sire":x.externalSireInfo||"","Dam":x.externalDamInfo||"","Latest weight":x.currentWeight??"","Last known group":x.managementGroup||"","Buyer/recipient":"","Price":"","Notes":x.notes||""}));
